# Generated by Django 2.1.7 on 2019-04-13 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_exercicio', models.PositiveSmallIntegerField()),
                ('fatia_de_mercado', models.FloatField()),
                ('novos_clientes_no_ano', models.FloatField()),
                ('novos_clientes', models.FloatField()),
                ('propostas_enviadas', models.FloatField()),
                ('assertividade_de_propostas', models.FloatField(default=1.0)),
                ('ticket_medio', models.FloatField(default=1.0)),
                ('aumento_de_vendas', models.FloatField(default=1.0)),
                ('clientes_fidelizados', models.FloatField()),
                ('contatos_proativos', models.FloatField()),
                ('reclamacoes_no_ano', models.FloatField()),
                ('reclamacoes_qtd_vendida', models.FloatField()),
                ('reclamacoes_clientes', models.FloatField()),
                ('nivel_de_satisfacao', models.FloatField()),
                ('clientes_perdidos', models.FloatField()),
                ('clientes_potenciais', models.FloatField(default=1.0)),
                ('market_share', models.FloatField(default=1.0)),
                ('retencao_de_clientes', models.FloatField(default=1.0)),
                ('qtd_produtos_servicos_vendidos', models.FloatField(default=1.0)),
                ('satisfacao_do_cliente', models.FloatField(default=1.0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analise de Vendas',
                'verbose_name_plural': 'Analises de Vendas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='vendas',
            unique_together={('user', 'ano_exercicio')},
        ),
    ]
