# Generated by Django 2.1.7 on 2019-04-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20190415_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='propostas_aprovadas_no_ano',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
