# Generated by Django 2.1.7 on 2019-04-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_vendas_propostas_aprovadas_no_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoVendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carteira_de_clientes_ativa', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('novos_clientes_no_ano', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('propostas_enviadas_no_ano', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('propostas_aprovadas_no_ano', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('notas_fiscais_emitidas', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('clientes_fidelizados', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('reclamacoes_clientes', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('clientes_perdidos', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('vendas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendas.Vendas')),
            ],
            options={
                'verbose_name': 'Avaliação da Analise de Vendas',
                'verbose_name_plural': 'Avaliações das Analises de Vendas',
            },
        ),
    ]
