# Generated by Django 2.1.7 on 2019-04-18 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engajamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engajamento', models.CharField(max_length=64)),
                ('categoria', models.CharField(choices=[('Excelente', 'Excelente'), ('Bom', 'Bom'), ('Baixa', 'Baixa'), ('Ruim', 'Ruim')], default='Baixa', max_length=12)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engajamento',
                'verbose_name_plural': 'Engajamentos',
            },
        ),
        migrations.AlterField(
            model_name='competencia',
            name='categoria',
            field=models.CharField(choices=[('Plena', 'Plena'), ('Parcial', 'Parcial'), ('Deficiente', 'Deficiente')], default='Parcial', max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='engajamento',
            unique_together={('user', 'engajamento')},
        ),
    ]
