# Generated by Django 2.1.7 on 2019-04-18 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoa', '0002_auto_20190417_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retencao', models.CharField(max_length=64)),
                ('categoria', models.CharField(choices=[('Implantado e Eficaz', 'Implantado e Eficaz'), ('Implantado e Parcial', 'Implantado e Parcial'), ('Em implantação', 'Em implantação'), ('Não implantado', 'Não implantado')], default='Em implantação', max_length=12)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retencao',
                'verbose_name_plural': 'Retencoes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='retencao',
            unique_together={('user', 'retencao')},
        ),
    ]
