# Generated by Django 2.1.7 on 2019-04-18 02:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoa', '0003_auto_20190417_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competencia',
            new_name='Competencias',
        ),
    ]
