# Generated by Django 2.1.7 on 2019-04-18 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoa', '0004_auto_20190417_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoPessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionarios_antigos', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('rotatividade', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('absenteismo', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
            ],
            options={
                'verbose_name': 'Avaliação da Analise de Pessoas',
                'verbose_name_plural': 'Avaliações das Analises de Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_exercicio', models.PositiveSmallIntegerField()),
                ('funcionarios_antigos', models.FloatField()),
                ('rotatividade', models.FloatField()),
                ('absenteismo', models.FloatField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analise de Pessoas',
                'verbose_name_plural': 'Analises de Pessoas',
            },
        ),
        migrations.AddField(
            model_name='avaliacaopessoas',
            name='pessoas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoas'),
        ),
        migrations.AlterUniqueTogether(
            name='pessoas',
            unique_together={('user', 'ano_exercicio')},
        ),
    ]
