# Generated by Django 2.1.5 on 2019-05-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_auto_20190418_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaopessoas',
            name='engajamento',
            field=models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6),
        ),
        migrations.AddField(
            model_name='avaliacaopessoas',
            name='nivel_competencias',
            field=models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6),
        ),
        migrations.AddField(
            model_name='avaliacaopessoas',
            name='retencao',
            field=models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6),
        ),
    ]
