# Generated by Django 2.1.7 on 2019-04-17 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoProcessos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionarios', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('volume_produzido_no_ano', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('capacidade_produzida', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('refugo_retrabalho', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('custos_garantia', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('entregas_no_prazo', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('reclamacoes_clientes', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
                ('valor_do_estoque', models.CharField(choices=[('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Neutro', 'Neutro')], default='Neutro', max_length=6)),
            ],
            options={
                'verbose_name': 'Avaliação da Analise de Processos',
                'verbose_name_plural': 'Avaliações das Analises de Processos',
            },
        ),
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_exercicio', models.PositiveSmallIntegerField()),
                ('funcionarios', models.FloatField()),
                ('volume_produzido_no_ano', models.FloatField()),
                ('capacidade_produzida', models.FloatField()),
                ('refugo_retrabalho', models.FloatField()),
                ('custos_garantia', models.FloatField(default=1.0)),
                ('entregas_no_prazo', models.FloatField()),
                ('reclamacoes_clientes', models.FloatField()),
                ('valor_do_estoque', models.FloatField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analise de Processos',
                'verbose_name_plural': 'Analises de Processos',
            },
        ),
        migrations.AddField(
            model_name='avaliacaoprocessos',
            name='processos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='processos_produtivo.Processos'),
        ),
        migrations.AlterUniqueTogether(
            name='processos',
            unique_together={('user', 'ano_exercicio')},
        ),
    ]
